/*
 * Provider API Documentation
 * Anthem Modernize Migration Microservices Provider API Documentation
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.anthem.provider.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * BillingData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-11T21:07:21.986Z")
public class BillingData {
  
 @JsonProperty("billiDate")
  private List<Long> billiDate = null;

  @JsonProperty("billingKey")
  private String billingKey = null;

  @JsonProperty("billingNumber")
  private String billingNumber = null;

  @JsonProperty("billingSource")
  private String billingSource = null;

  @JsonProperty("billingState")
  private String billingState = null;

  @JsonProperty("billingType")
  private String billingType = null;

  public BillingData billiDate(List<Long> billiDate) {
    this.billiDate = billiDate;
    return this;
  }

  public BillingData addBilliDateItem(Long billiDateItem) {
    if (this.billiDate == null) {
      this.billiDate = new ArrayList<Long>();
    }
    this.billiDate.add(billiDateItem);
    return this;
  }

   /**
   * Billing dates
   * @return billiDate
  **/
  @ApiModelProperty(value = "Billing dates")
  public List<Long> getBilliDate() {
    return billiDate;
  }

  public void setBilliDate(List<Long> billiDate) {
    this.billiDate = billiDate;
  }

  public BillingData billingKey(String billingKey) {
    this.billingKey = billingKey;
    return this;
  }

   /**
   * Billing key
   * @return billingKey
  **/
  @ApiModelProperty(value = "Billing key")
  public String getBillingKey() {
    return billingKey;
  }

  public void setBillingKey(String billingKey) {
    this.billingKey = billingKey;
  }

  public BillingData billingNumber(String billingNumber) {
    this.billingNumber = billingNumber;
    return this;
  }

   /**
   * Tax id or Medicare id value
   * @return billingNumber
  **/
  @ApiModelProperty(value = "Tax id or Medicare id value")
  public String getBillingNumber() {
    return billingNumber;
  }

  public void setBillingNumber(String billingNumber) {
    this.billingNumber = billingNumber;
  }

  public BillingData billingSource(String billingSource) {
    this.billingSource = billingSource;
    return this;
  }

   /**
   * Tax id or institutional id
   * @return billingSource
  **/
  @ApiModelProperty(value = "Tax id or institutional id")
  public String getBillingSource() {
    return billingSource;
  }

  public void setBillingSource(String billingSource) {
    this.billingSource = billingSource;
  }

  public BillingData billingState(String billingState) {
    this.billingState = billingState;
    return this;
  }

   /**
   * Billing state
   * @return billingState
  **/
  @ApiModelProperty(value = "Billing state")
  public String getBillingState() {
    return billingState;
  }

  public void setBillingState(String billingState) {
    this.billingState = billingState;
  }

  public BillingData billingType(String billingType) {
    this.billingType = billingType;
    return this;
  }

   /**
   * Billing type
   * @return billingType
  **/
  @ApiModelProperty(value = "Billing type")
  public String getBillingType() {
    return billingType;
  }

  public void setBillingType(String billingType) {
    this.billingType = billingType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingData billingData = (BillingData) o;
    return Objects.equals(this.billiDate, billingData.billiDate) &&
        Objects.equals(this.billingKey, billingData.billingKey) &&
        Objects.equals(this.billingNumber, billingData.billingNumber) &&
        Objects.equals(this.billingSource, billingData.billingSource) &&
        Objects.equals(this.billingState, billingData.billingState) &&
        Objects.equals(this.billingType, billingData.billingType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billiDate, billingKey, billingNumber, billingSource, billingState, billingType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingData {\n");
    
    sb.append("    billiDate: ").append(toIndentedString(billiDate)).append("\n");
    sb.append("    billingKey: ").append(toIndentedString(billingKey)).append("\n");
    sb.append("    billingNumber: ").append(toIndentedString(billingNumber)).append("\n");
    sb.append("    billingSource: ").append(toIndentedString(billingSource)).append("\n");
    sb.append("    billingState: ").append(toIndentedString(billingState)).append("\n");
    sb.append("    billingType: ").append(toIndentedString(billingType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

