/*
 * Provider API Documentation
 * Anthem Modernize Migration Microservices Provider API Documentation
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.anthem.provider.domain;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CopybookRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-11T21:07:21.986Z")
public class CopybookRequest {
  @JsonProperty("serviceFromDate")
  private Long serviceFromDate = null;

  @JsonProperty("serviceThroughDate")
  private Long serviceThroughDate = null;

  @JsonProperty("billingNumber")
  private String billingNumber = null;

  @JsonProperty("renderingNumber")
  private String renderingNumber = null;

  @JsonProperty("providerLOBCode")
  private String providerLOBCode = null;

  @JsonProperty("companyCode")
  private String companyCode = null;

  @JsonProperty("claimType")
  private String claimType = null;

  @JsonProperty("exchangeIndicator")
  private String exchangeIndicator = null;

  @JsonProperty("conversionCode")
  private String conversionCode = null;

  @JsonProperty("nationalProviderState")
  private String nationalProviderState = null;

  @JsonProperty("providerDataSource")
  private String providerDataSource = null;

  @JsonProperty("hostStateId")
  private String hostStateId = null;

  @JsonProperty("itemCode")
  private String itemCode = null;

  @JsonProperty("claimReceivedDate")
  private Long claimReceivedDate = null;

  @JsonProperty("servicingProviderState")
  private String servicingProviderState = null;

  @JsonProperty("taxOrInstitutionalId")
  private String taxOrInstitutionalId = null;

  @JsonProperty("billingType")
  private String billingType = null;

  @JsonProperty("billingState")
  private String billingState = null;

  @JsonProperty("LicOrHmoId")
  private String licOrHmoId = null;

  @JsonProperty("renderingType")
  private String renderingType = null;

  @JsonProperty("renderingState")
  private String renderingState = null;

  @JsonProperty("wgspIndicatorEnable")
  private String wgspIndicatorEnable = null;

  @JsonProperty("wsgpIndicatorExclusion")
  private String wsgpIndicatorExclusion = null;

  @JsonProperty("systemName")
  private String systemName = null;

  @JsonProperty("adjustmentSoruceDate")
  private Long adjustmentSoruceDate = null;

  @JsonProperty("claimMedicareOrLICDate")
  private String claimMedicareOrLICDate = null;

  @JsonProperty("adjustmentReasonCode")
  private String adjustmentReasonCode = null;

  public CopybookRequest serviceFromDate(Long serviceFromDate) {
    this.serviceFromDate = serviceFromDate;
    return this;
  }

   /**
   * Service from date from the claim
   * @return serviceFromDate
  **/
  @ApiModelProperty(required = true, value = "Service from date from the claim")
  public Long getServiceFromDate() {
    return serviceFromDate;
  }

  public void setServiceFromDate(Long serviceFromDate) {
    this.serviceFromDate = serviceFromDate;
  }

  public CopybookRequest serviceThroughDate(Long serviceThroughDate) {
    this.serviceThroughDate = serviceThroughDate;
    return this;
  }

   /**
   * Service through date from the claim
   * @return serviceThroughDate
  **/
  @ApiModelProperty(required = true, value = "Service through date from the claim")
  public Long getServiceThroughDate() {
    return serviceThroughDate;
  }

  public void setServiceThroughDate(Long serviceThroughDate) {
    this.serviceThroughDate = serviceThroughDate;
  }

  public CopybookRequest billingNumber(String billingNumber) {
    this.billingNumber = billingNumber;
    return this;
  }

   /**
   * Billing number
   * @return billingNumber
  **/
  @ApiModelProperty(required = true, value = "Billing number")
  public String getBillingNumber() {
    return billingNumber;
  }

  public void setBillingNumber(String billingNumber) {
    this.billingNumber = billingNumber;
  }

  public CopybookRequest renderingNumber(String renderingNumber) {
    this.renderingNumber = renderingNumber;
    return this;
  }

   /**
   * Rendering number
   * @return renderingNumber
  **/
  @ApiModelProperty(required = true, value = "Rendering number")
  public String getRenderingNumber() {
    return renderingNumber;
  }

  public void setRenderingNumber(String renderingNumber) {
    this.renderingNumber = renderingNumber;
  }

  public CopybookRequest providerLOBCode(String providerLOBCode) {
    this.providerLOBCode = providerLOBCode;
    return this;
  }

   /**
   * Provider LOB code
   * @return providerLOBCode
  **/
  @ApiModelProperty(required = true, value = "Provider LOB code")
  public String getProviderLOBCode() {
    return providerLOBCode;
  }

  public void setProviderLOBCode(String providerLOBCode) {
    this.providerLOBCode = providerLOBCode;
  }

  public CopybookRequest companyCode(String companyCode) {
    this.companyCode = companyCode;
    return this;
  }

   /**
   * Company code
   * @return companyCode
  **/
  @ApiModelProperty(required = true, value = "Company code")
  public String getCompanyCode() {
    return companyCode;
  }

  public void setCompanyCode(String companyCode) {
    this.companyCode = companyCode;
  }

  public CopybookRequest claimType(String claimType) {
    this.claimType = claimType;
    return this;
  }

   /**
   * Professional or hospital claims
   * @return claimType
  **/
  @ApiModelProperty(required = true, value = "Professional or hospital claims")
  public String getClaimType() {
    return claimType;
  }

  public void setClaimType(String claimType) {
    this.claimType = claimType;
  }

  public CopybookRequest exchangeIndicator(String exchangeIndicator) {
    this.exchangeIndicator = exchangeIndicator;
    return this;
  }

   /**
   * HIX or non-HIX claims
   * @return exchangeIndicator
  **/
  @ApiModelProperty(required = true, value = "HIX or non-HIX claims")
  public String getExchangeIndicator() {
    return exchangeIndicator;
  }

  public void setExchangeIndicator(String exchangeIndicator) {
    this.exchangeIndicator = exchangeIndicator;
  }

  public CopybookRequest conversionCode(String conversionCode) {
    this.conversionCode = conversionCode;
    return this;
  }

   /**
   * Conversion code of whether the member is from ACES, CHIPS or CS90
   * @return conversionCode
  **/
  @ApiModelProperty(required = true, value = "Conversion code of whether the member is from ACES, CHIPS or CS90")
  public String getConversionCode() {
    return conversionCode;
  }

  public void setConversionCode(String conversionCode) {
    this.conversionCode = conversionCode;
  }

  public CopybookRequest nationalProviderState(String nationalProviderState) {
    this.nationalProviderState = nationalProviderState;
    return this;
  }

   /**
   * National provider state
   * @return nationalProviderState
  **/
  @ApiModelProperty(required = true, value = "National provider state")
  public String getNationalProviderState() {
    return nationalProviderState;
  }

  public void setNationalProviderState(String nationalProviderState) {
    this.nationalProviderState = nationalProviderState;
  }

  public CopybookRequest providerDataSource(String providerDataSource) {
    this.providerDataSource = providerDataSource;
    return this;
  }

   /**
   * Denotes of whether the provider resides in WGSP or not
   * @return providerDataSource
  **/
  @ApiModelProperty(required = true, value = "Denotes of whether the provider resides in WGSP or not")
  public String getProviderDataSource() {
    return providerDataSource;
  }

  public void setProviderDataSource(String providerDataSource) {
    this.providerDataSource = providerDataSource;
  }

  public CopybookRequest hostStateId(String hostStateId) {
    this.hostStateId = hostStateId;
    return this;
  }

   /**
   * ITS host state
   * @return hostStateId
  **/
  @ApiModelProperty(required = true, value = "ITS host state")
  public String getHostStateId() {
    return hostStateId;
  }

  public void setHostStateId(String hostStateId) {
    this.hostStateId = hostStateId;
  }

  public CopybookRequest itemCode(String itemCode) {
    this.itemCode = itemCode;
    return this;
  }

   /**
   * Regular or Adjusted claim
   * @return itemCode
  **/
  @ApiModelProperty(required = true, value = "Regular or Adjusted claim")
  public String getItemCode() {
    return itemCode;
  }

  public void setItemCode(String itemCode) {
    this.itemCode = itemCode;
  }

  public CopybookRequest claimReceivedDate(Long claimReceivedDate) {
    this.claimReceivedDate = claimReceivedDate;
    return this;
  }

   /**
   * Date on when the claim received first in WGS
   * @return claimReceivedDate
  **/
  @ApiModelProperty(required = true, value = "Date on when the claim received first in WGS")
  public Long getClaimReceivedDate() {
    return claimReceivedDate;
  }

  public void setClaimReceivedDate(Long claimReceivedDate) {
    this.claimReceivedDate = claimReceivedDate;
  }

  public CopybookRequest servicingProviderState(String servicingProviderState) {
    this.servicingProviderState = servicingProviderState;
    return this;
  }

   /**
   * Servicing provider state
   * @return servicingProviderState
  **/
  @ApiModelProperty(required = true, value = "Servicing provider state")
  public String getServicingProviderState() {
    return servicingProviderState;
  }

  public void setServicingProviderState(String servicingProviderState) {
    this.servicingProviderState = servicingProviderState;
  }

  public CopybookRequest taxOrInstitutionalId(String taxOrInstitutionalId) {
    this.taxOrInstitutionalId = taxOrInstitutionalId;
    return this;
  }

   /**
   * Indicator to fetch Tax id or institutional id
   * @return taxOrInstitutionalId
  **/
  @ApiModelProperty(value = "Indicator to fetch Tax id or institutional id")
  public String getTaxOrInstitutionalId() {
    return taxOrInstitutionalId;
  }

  public void setTaxOrInstitutionalId(String taxOrInstitutionalId) {
    this.taxOrInstitutionalId = taxOrInstitutionalId;
  }

  public CopybookRequest billingType(String billingType) {
    this.billingType = billingType;
    return this;
  }

   /**
   * Billing type of whether it is facet id or Medicare or Medicaid etc
   * @return billingType
  **/
  @ApiModelProperty(value = "Billing type of whether it is facet id or Medicare or Medicaid etc")
  public String getBillingType() {
    return billingType;
  }

  public void setBillingType(String billingType) {
    this.billingType = billingType;
  }

  public CopybookRequest billingState(String billingState) {
    this.billingState = billingState;
    return this;
  }

   /**
   * Billing state
   * @return billingState
  **/
  @ApiModelProperty(value = "Billing state")
  public String getBillingState() {
    return billingState;
  }

  public void setBillingState(String billingState) {
    this.billingState = billingState;
  }

  public CopybookRequest licOrHmoId(String licOrHmoId) {
    this.licOrHmoId = licOrHmoId;
    return this;
  }

   /**
   * Indicator to fetch LIC or HMO id
   * @return licOrHmoId
  **/
  @ApiModelProperty(value = "Indicator to fetch LIC or HMO id")
  public String getLicOrHmoId() {
    return licOrHmoId;
  }

  public void setLicOrHmoId(String licOrHmoId) {
    this.licOrHmoId = licOrHmoId;
  }

  public CopybookRequest renderingType(String renderingType) {
    this.renderingType = renderingType;
    return this;
  }

   /**
   * Rendering type of whether it is facet id or Medicare or Medicaid etc
   * @return renderingType
  **/
  @ApiModelProperty(value = "Rendering type of whether it is facet id or Medicare or Medicaid etc")
  public String getRenderingType() {
    return renderingType;
  }

  public void setRenderingType(String renderingType) {
    this.renderingType = renderingType;
  }

  public CopybookRequest renderingState(String renderingState) {
    this.renderingState = renderingState;
    return this;
  }

   /**
   * Rendering state
   * @return renderingState
  **/
  @ApiModelProperty(value = "Rendering state")
  public String getRenderingState() {
    return renderingState;
  }

  public void setRenderingState(String renderingState) {
    this.renderingState = renderingState;
  }

  public CopybookRequest wgspIndicatorEnable(String wgspIndicatorEnable) {
    this.wgspIndicatorEnable = wgspIndicatorEnable;
    return this;
  }

   /**
   * Indicator to call the provider IO
   * @return wgspIndicatorEnable
  **/
  @ApiModelProperty(value = "Indicator to call the provider IO")
  public String getWgspIndicatorEnable() {
    return wgspIndicatorEnable;
  }

  public void setWgspIndicatorEnable(String wgspIndicatorEnable) {
    this.wgspIndicatorEnable = wgspIndicatorEnable;
  }

  public CopybookRequest wsgpIndicatorExclusion(String wsgpIndicatorExclusion) {
    this.wsgpIndicatorExclusion = wsgpIndicatorExclusion;
    return this;
  }

   /**
   * Indicator to call the provider IO
   * @return wsgpIndicatorExclusion
  **/
  @ApiModelProperty(value = "Indicator to call the provider IO")
  public String getWsgpIndicatorExclusion() {
    return wsgpIndicatorExclusion;
  }

  public void setWsgpIndicatorExclusion(String wsgpIndicatorExclusion) {
    this.wsgpIndicatorExclusion = wsgpIndicatorExclusion;
  }

  public CopybookRequest systemName(String systemName) {
    this.systemName = systemName;
    return this;
  }

   /**
   * To denote claims system or any other system
   * @return systemName
  **/
  @ApiModelProperty(value = "To denote claims system or any other system")
  public String getSystemName() {
    return systemName;
  }

  public void setSystemName(String systemName) {
    this.systemName = systemName;
  }

  public CopybookRequest adjustmentSoruceDate(Long adjustmentSoruceDate) {
    this.adjustmentSoruceDate = adjustmentSoruceDate;
    return this;
  }

   /**
   * Date of the claim when the regular claim was finalized. Value required when claim is adjusted
   * @return adjustmentSoruceDate
  **/
  @ApiModelProperty(value = "Date of the claim when the regular claim was finalized. Value required when claim is adjusted")
  public Long getAdjustmentSoruceDate() {
    return adjustmentSoruceDate;
  }

  public void setAdjustmentSoruceDate(Long adjustmentSoruceDate) {
    this.adjustmentSoruceDate = adjustmentSoruceDate;
  }

  public CopybookRequest claimMedicareOrLICDate(String claimMedicareOrLICDate) {
    this.claimMedicareOrLICDate = claimMedicareOrLICDate;
    return this;
  }

   /**
   * Original claim provider info
   * @return claimMedicareOrLICDate
  **/
  @ApiModelProperty(value = "Original claim provider info")
  public String getClaimMedicareOrLICDate() {
    return claimMedicareOrLICDate;
  }

  public void setClaimMedicareOrLICDate(String claimMedicareOrLICDate) {
    this.claimMedicareOrLICDate = claimMedicareOrLICDate;
  }

  public CopybookRequest adjustmentReasonCode(String adjustmentReasonCode) {
    this.adjustmentReasonCode = adjustmentReasonCode;
    return this;
  }

   /**
   * Claim adjustment reason code
   * @return adjustmentReasonCode
  **/
  @ApiModelProperty(value = "Claim adjustment reason code")
  public String getAdjustmentReasonCode() {
    return adjustmentReasonCode;
  }

  public void setAdjustmentReasonCode(String adjustmentReasonCode) {
    this.adjustmentReasonCode = adjustmentReasonCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CopybookRequest copybookRequest = (CopybookRequest) o;
    return Objects.equals(this.serviceFromDate, copybookRequest.serviceFromDate) &&
        Objects.equals(this.serviceThroughDate, copybookRequest.serviceThroughDate) &&
        Objects.equals(this.billingNumber, copybookRequest.billingNumber) &&
        Objects.equals(this.renderingNumber, copybookRequest.renderingNumber) &&
        Objects.equals(this.providerLOBCode, copybookRequest.providerLOBCode) &&
        Objects.equals(this.companyCode, copybookRequest.companyCode) &&
        Objects.equals(this.claimType, copybookRequest.claimType) &&
        Objects.equals(this.exchangeIndicator, copybookRequest.exchangeIndicator) &&
        Objects.equals(this.conversionCode, copybookRequest.conversionCode) &&
        Objects.equals(this.nationalProviderState, copybookRequest.nationalProviderState) &&
        Objects.equals(this.providerDataSource, copybookRequest.providerDataSource) &&
        Objects.equals(this.hostStateId, copybookRequest.hostStateId) &&
        Objects.equals(this.itemCode, copybookRequest.itemCode) &&
        Objects.equals(this.claimReceivedDate, copybookRequest.claimReceivedDate) &&
        Objects.equals(this.servicingProviderState, copybookRequest.servicingProviderState) &&
        Objects.equals(this.taxOrInstitutionalId, copybookRequest.taxOrInstitutionalId) &&
        Objects.equals(this.billingType, copybookRequest.billingType) &&
        Objects.equals(this.billingState, copybookRequest.billingState) &&
        Objects.equals(this.licOrHmoId, copybookRequest.licOrHmoId) &&
        Objects.equals(this.renderingType, copybookRequest.renderingType) &&
        Objects.equals(this.renderingState, copybookRequest.renderingState) &&
        Objects.equals(this.wgspIndicatorEnable, copybookRequest.wgspIndicatorEnable) &&
        Objects.equals(this.wsgpIndicatorExclusion, copybookRequest.wsgpIndicatorExclusion) &&
        Objects.equals(this.systemName, copybookRequest.systemName) &&
        Objects.equals(this.adjustmentSoruceDate, copybookRequest.adjustmentSoruceDate) &&
        Objects.equals(this.claimMedicareOrLICDate, copybookRequest.claimMedicareOrLICDate) &&
        Objects.equals(this.adjustmentReasonCode, copybookRequest.adjustmentReasonCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceFromDate, serviceThroughDate, billingNumber, renderingNumber, providerLOBCode, companyCode, claimType, exchangeIndicator, conversionCode, nationalProviderState, providerDataSource, hostStateId, itemCode, claimReceivedDate, servicingProviderState, taxOrInstitutionalId, billingType, billingState, licOrHmoId, renderingType, renderingState, wgspIndicatorEnable, wsgpIndicatorExclusion, systemName, adjustmentSoruceDate, claimMedicareOrLICDate, adjustmentReasonCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CopybookRequest {\n");
    
    sb.append("    serviceFromDate: ").append(toIndentedString(serviceFromDate)).append("\n");
    sb.append("    serviceThroughDate: ").append(toIndentedString(serviceThroughDate)).append("\n");
    sb.append("    billingNumber: ").append(toIndentedString(billingNumber)).append("\n");
    sb.append("    renderingNumber: ").append(toIndentedString(renderingNumber)).append("\n");
    sb.append("    providerLOBCode: ").append(toIndentedString(providerLOBCode)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    claimType: ").append(toIndentedString(claimType)).append("\n");
    sb.append("    exchangeIndicator: ").append(toIndentedString(exchangeIndicator)).append("\n");
    sb.append("    conversionCode: ").append(toIndentedString(conversionCode)).append("\n");
    sb.append("    nationalProviderState: ").append(toIndentedString(nationalProviderState)).append("\n");
    sb.append("    providerDataSource: ").append(toIndentedString(providerDataSource)).append("\n");
    sb.append("    hostStateId: ").append(toIndentedString(hostStateId)).append("\n");
    sb.append("    itemCode: ").append(toIndentedString(itemCode)).append("\n");
    sb.append("    claimReceivedDate: ").append(toIndentedString(claimReceivedDate)).append("\n");
    sb.append("    servicingProviderState: ").append(toIndentedString(servicingProviderState)).append("\n");
    sb.append("    taxOrInstitutionalId: ").append(toIndentedString(taxOrInstitutionalId)).append("\n");
    sb.append("    billingType: ").append(toIndentedString(billingType)).append("\n");
    sb.append("    billingState: ").append(toIndentedString(billingState)).append("\n");
    sb.append("    licOrHmoId: ").append(toIndentedString(licOrHmoId)).append("\n");
    sb.append("    renderingType: ").append(toIndentedString(renderingType)).append("\n");
    sb.append("    renderingState: ").append(toIndentedString(renderingState)).append("\n");
    sb.append("    wgspIndicatorEnable: ").append(toIndentedString(wgspIndicatorEnable)).append("\n");
    sb.append("    wsgpIndicatorExclusion: ").append(toIndentedString(wsgpIndicatorExclusion)).append("\n");
    sb.append("    systemName: ").append(toIndentedString(systemName)).append("\n");
    sb.append("    adjustmentSoruceDate: ").append(toIndentedString(adjustmentSoruceDate)).append("\n");
    sb.append("    claimMedicareOrLICDate: ").append(toIndentedString(claimMedicareOrLICDate)).append("\n");
    sb.append("    adjustmentReasonCode: ").append(toIndentedString(adjustmentReasonCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

