/*
 * Provider API Documentation
 * Anthem Modernize Migration Microservices Provider API Documentation
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.anthem.provider.domain;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * CopybookResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-11T21:07:21.986Z")
public class CopybookResponse {
  @JsonProperty("billingData")
  private BillingData billingData = null;

  @JsonProperty("billingStatusCode")
  private String billingStatusCode = null;

  @JsonProperty("renderingData")
  private RenderingData renderingData = null;

  @JsonProperty("renderingStatusCode")
  private String renderingStatusCode = null;

  @JsonProperty("dataFromIndicator")
  private String dataFromIndicator = null;

  @JsonProperty("wsgpErrorCode")
  private String wsgpErrorCode = null;

  public CopybookResponse billingData(BillingData billingData) {
    this.billingData = billingData;
    return this;
  }

   /**
   * Get billingData
   * @return billingData
  **/
  @ApiModelProperty(value = "")
  public BillingData getBillingData() {
    return billingData;
  }

  public void setBillingData(BillingData billingData) {
    this.billingData = billingData;
  }

  public CopybookResponse billingStatusCode(String billingStatusCode) {
    this.billingStatusCode = billingStatusCode;
    return this;
  }

   /**
   * exceptions to handle edit and errors
   * @return billingStatusCode
  **/
  @ApiModelProperty(value = "exceptions to handle edit and errors")
  public String getBillingStatusCode() {
    return billingStatusCode;
  }

  public void setBillingStatusCode(String billingStatusCode) {
    this.billingStatusCode = billingStatusCode;
  }

  public CopybookResponse renderingData(RenderingData renderingData) {
    this.renderingData = renderingData;
    return this;
  }

   /**
   * Get renderingData
   * @return renderingData
  **/
  @ApiModelProperty(value = "")
  public RenderingData getRenderingData() {
    return renderingData;
  }

  public void setRenderingData(RenderingData renderingData) {
    this.renderingData = renderingData;
  }

  public CopybookResponse renderingStatusCode(String renderingStatusCode) {
    this.renderingStatusCode = renderingStatusCode;
    return this;
  }

   /**
   * exceptions to handle edit and errors
   * @return renderingStatusCode
  **/
  @ApiModelProperty(value = "exceptions to handle edit and errors")
  public String getRenderingStatusCode() {
    return renderingStatusCode;
  }

  public void setRenderingStatusCode(String renderingStatusCode) {
    this.renderingStatusCode = renderingStatusCode;
  }

  public CopybookResponse dataFromIndicator(String dataFromIndicator) {
    this.dataFromIndicator = dataFromIndicator;
    return this;
  }

   /**
   * To handle any exceptions
   * @return dataFromIndicator
  **/
  @ApiModelProperty(value = "To handle any exceptions")
  public String getDataFromIndicator() {
    return dataFromIndicator;
  }

  public void setDataFromIndicator(String dataFromIndicator) {
    this.dataFromIndicator = dataFromIndicator;
  }

  public CopybookResponse wsgpErrorCode(String wsgpErrorCode) {
    this.wsgpErrorCode = wsgpErrorCode;
    return this;
  }

   /**
   * To handle any exceptions
   * @return wsgpErrorCode
  **/
  @ApiModelProperty(value = "To handle any exceptions")
  public String getWsgpErrorCode() {
    return wsgpErrorCode;
  }

  public void setWsgpErrorCode(String wsgpErrorCode) {
    this.wsgpErrorCode = wsgpErrorCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CopybookResponse copybookResponse = (CopybookResponse) o;
    return Objects.equals(this.billingData, copybookResponse.billingData) &&
        Objects.equals(this.billingStatusCode, copybookResponse.billingStatusCode) &&
        Objects.equals(this.renderingData, copybookResponse.renderingData) &&
        Objects.equals(this.renderingStatusCode, copybookResponse.renderingStatusCode) &&
        Objects.equals(this.dataFromIndicator, copybookResponse.dataFromIndicator) &&
        Objects.equals(this.wsgpErrorCode, copybookResponse.wsgpErrorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billingData, billingStatusCode, renderingData, renderingStatusCode, dataFromIndicator, wsgpErrorCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CopybookResponse {\n");
    
    sb.append("    billingData: ").append(toIndentedString(billingData)).append("\n");
    sb.append("    billingStatusCode: ").append(toIndentedString(billingStatusCode)).append("\n");
    sb.append("    renderingData: ").append(toIndentedString(renderingData)).append("\n");
    sb.append("    renderingStatusCode: ").append(toIndentedString(renderingStatusCode)).append("\n");
    sb.append("    dataFromIndicator: ").append(toIndentedString(dataFromIndicator)).append("\n");
    sb.append("    wsgpErrorCode: ").append(toIndentedString(wsgpErrorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

